---
format: revealjs
title: Hackathon2022slides
---

## {background-image="sortee2022/sortee2022_pdf - page 1.png"}
## {background-image="sortee2022/sortee2022_pdf - page 2.png"}
## {background-image="sortee2022/sortee2022_pdf - page 3.png"}
## {background-image="sortee2022/sortee2022_pdf - page 4.png"}
## {background-image="sortee2022/sortee2022_pdf - page 5.png"}
## {background-image="sortee2022/sortee2022_pdf - page 6.png"}
## {background-image="sortee2022/sortee2022_pdf - page 7.png"}
## {background-image="sortee2022/sortee2022_pdf - page 8.png"}
## {background-image="sortee2022/sortee2022_pdf - page 9.png"}
## {background-image="sortee2022/sortee2022_pdf - page 10.png"}
## {background-image="sortee2022/sortee2022_pdf - page 11.png"}
## {background-image="sortee2022/sortee2022_pdf - page 12.png"}
## {background-image="sortee2022/sortee2022_pdf - page 13.png"}
## {background-image="sortee2022/sortee2022_pdf - page 14.png"}
## {background-image="sortee2022/sortee2022_pdf - page 15.png"}
## {background-image="sortee2022/sortee2022_pdf - page 16.png"}
## {background-image="sortee2022/sortee2022_pdf - page 17.png"}
## {background-image="sortee2022/sortee2022_pdf - page 18.png"}
## {background-image="sortee2022/sortee2022_pdf - page 19.png"}
## {background-image="sortee2022/sortee2022_pdf - page 20.png"}
## {background-image="sortee2022/sortee2022_pdf - page 21.png"}
## {background-image="sortee2022/sortee2022_pdf - page 22.png"}
## {background-image="sortee2022/sortee2022_pdf - page 23.png"}
## {background-image="sortee2022/sortee2022_pdf - page 24.png"}
## {background-image="sortee2022/sortee2022_pdf - page 25.png"}
## {background-image="sortee2022/sortee2022_pdf - page 26.png"}
## {background-image="sortee2022/sortee2022_pdf - page 27.png"}
## {background-image="sortee2022/sortee2022_pdf - page 28.png"}
## {background-image="sortee2022/sortee2022_pdf - page 29.png"}
## {background-image="sortee2022/sortee2022_pdf - page 30.png"}
## {background-image="sortee2022/sortee2022_pdf - page 31.png"}
## {background-image="sortee2022/sortee2022_pdf - page 32.png"}
## {background-image="sortee2022/sortee2022_pdf - page 33.png"}
## {background-image="sortee2022/sortee2022_pdf - page 34.png"}
## {background-image="sortee2022/sortee2022_pdf - page 35.png"}
